// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJib366H3nund18cbOvi_OCDgh0K4X2k',
    appId: '1:190457478703:web:725d91e01a1fd00ee750da',
    messagingSenderId: '190457478703',
    projectId: 'seatsmart-64a2c',
    authDomain: 'seatsmart-64a2c.firebaseapp.com',
    storageBucket: 'seatsmart-64a2c.appspot.com',
    measurementId: 'G-CK72MRV97M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPif_fuTfZSX5BQrVdGOdeU_UT9tmKA4Y',
    appId: '1:190457478703:android:43fe1740a4d4aa4fe750da',
    messagingSenderId: '190457478703',
    projectId: 'seatsmart-64a2c',
    storageBucket: 'seatsmart-64a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRN51Saw58Wu7-2JYvmxxD6tkqO_d4t_o',
    appId: '1:190457478703:ios:ce4f668065ff1960e750da',
    messagingSenderId: '190457478703',
    projectId: 'seatsmart-64a2c',
    storageBucket: 'seatsmart-64a2c.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRN51Saw58Wu7-2JYvmxxD6tkqO_d4t_o',
    appId: '1:190457478703:ios:ce4f668065ff1960e750da',
    messagingSenderId: '190457478703',
    projectId: 'seatsmart-64a2c',
    storageBucket: 'seatsmart-64a2c.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzJib366H3nund18cbOvi_OCDgh0K4X2k',
    appId: '1:190457478703:web:8efc9bb1425ca8a7e750da',
    messagingSenderId: '190457478703',
    projectId: 'seatsmart-64a2c',
    authDomain: 'seatsmart-64a2c.firebaseapp.com',
    storageBucket: 'seatsmart-64a2c.appspot.com',
    measurementId: 'G-F2F80X62ZW',
  );
}
